import type React from 'react';
import { useState } from 'react';
import type { WojakCharacter } from '../types/wojak';
import { generateRandomWojak } from '../utils/wojakGenerator';
import { WojakCanvas } from './WojakCanvas';
import { WojakControls } from './WojakControls';
import { WojakPreview } from './WojakPreview';

interface WojakBuilderProps {
  onMint: (wojak: Omit<WojakCharacter, 'id' | 'createdAt'>) => void;
}

export const WojakBuilder: React.FC<WojakBuilderProps> = ({ onMint }) => {
  const [currentWojak, setCurrentWojak] = useState<WojakCharacter>(generateRandomWojak());
  const [selectedCategory, setSelectedCategory] = useState<string>('template');
  const [isMinting, setIsMinting] = useState(false);

  const handleWojakUpdate = (updatedWojak: Partial<WojakCharacter>) => {
    setCurrentWojak((prev) => ({ ...prev, ...updatedWojak }));
  };

  const handleRandomize = () => {
    setCurrentWojak(generateRandomWojak());
  };

  const handleClearAll = () => {
    setCurrentWojak({
      ...currentWojak,
      template: 'Standard',
      hat: 'none',
      glasses: 'none',
      mask: 'none',
      background: {
        color: '#FFFFFF',
        pattern: 'solid',
        patternColor: undefined,
      },
    });
  };

  const handleMint = async () => {
    if (!currentWojak.name || currentWojak.name.trim() === '') {
      alert('Please give your wojak a name before minting!');
      return;
    }

    setIsMinting(true);

    // Simulate minting process
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Remove id and createdAt as they'll be generated by the storage hook
    const { id: _id, createdAt: _createdAt, ...wojakToMint } = currentWojak;
    onMint(wojakToMint);

    setIsMinting(false);
  };

  return (
    <div className="flex h-full flex-col">
      <div className="grid min-h-0 flex-1 grid-cols-1 gap-4 lg:grid-cols-2">
        {/* Left Column - Two rows */}
        <div className="flex h-full min-h-0 flex-col space-y-3">
          {/* Row 1: Canvas */}
          <div className="min-h-0 flex-1">
            <WojakCanvas wojak={currentWojak} onUpdate={handleWojakUpdate} />
          </div>

          {/* Row 2: Actions */}
          <div className="flex-shrink-0">
            <WojakPreview wojak={currentWojak} onMint={handleMint} isMinting={isMinting} />
          </div>
        </div>

        {/* Right Column - One row */}
        <div className="flex h-full min-h-0 flex-col">
          <WojakControls
            wojak={currentWojak}
            selectedCategory={selectedCategory}
            onCategoryChange={setSelectedCategory}
            onWojakUpdate={handleWojakUpdate}
            onRandomize={handleRandomize}
            onClearAll={handleClearAll}
          />
        </div>
      </div>
    </div>
  );
};
